### ISSUE TITLE
Missing typedef or struct.

### ISSUE THREAD

**Issue by spongeboburu** [mackron/fs#1]
```
fs.c:4460:13: error: unknown type name ‘fs_stdio_file_args’; use ‘struct’ keyword to refer to the type
    fs_stdio_file_args* pArgsFile = (fs_stdio_file_args*)pArgs;
```

Right now I'm patching fs.h to typedef `fs_stdio_file_args` in my cmake external project patch step. Another fix would be (as gcc suggests) to add the struct keyword in the type declaration.

Have a nice day!

**Comment by mackron** [comment]
Thanks for the report. This should be fixed.
